### ISSUE TITLE
check out if your jars numbers is not 42

### ISSUE THREAD

**Issue by SyloYamtao** [Sunybyjava/employeeManager#1]
I feel that you put less jar than you really need .Course i deploy on my tomcat nest a exception that "**Exception thrown from ApplicationListener handling ContextClosedEvent
java.lang.IllegalStateException: ApplicationEventMulticaster not initialized - call 'refresh' before multicasting events via the context: Root WebApplicationContext: startup date [Fri May 12 17:53:23 CST 2017]; root of context hierarchy**"
please check out and update ASAP.
otherwise,i strongly recommend you Maven or Gradle to manage your employeeManager Project's  build.
all the best!

**Comment by sjr7** [comment]
Thanks for you reminder, I have changed the project to maven build , Just now , The project is deploy on tomcat , Welcome to point out the inadeequacies
