### ISSUE TITLE
After Deploy ,HTTP ERROR 404

### ISSUE THREAD

**Issue by SyloYamtao** [Sunybyjava/employeeManager#2]
Thank you for your working-hard updating.But i have some new problems for you.
1) Maven finds out that **org.hibernate:hibernate-commons-annotations.4.3.11.jar** cannot find in any Repositories in the web,so i take  **org.hibernate.common : hibernate-commons-annotations . 5.0.1.Final**insteaded,maven complied successfully without any exceptions.
2) after deploy on jetty,when i press url like **http://localhost:8080/user/loginPage** which i find in your Controller-code in the url bar,it always appealing "HTTP ERROR 404";and my jetty port is 8080;
LOOKING FORWARD YOUR ANSWER.
Happy Coding!

**Comment by sjr7** [comment]
For your issue
- The  **org.hibernate:hibernate-commons-annotations.4.3.11.jar** is read from the maven local repository , On the [http://mvnrepository.com](url) , The [http://mvnrepository.com/artifact/org.hibernate/hibernate-commons-annotations](url) is the old repository address,This artifact was moved to:[http://mvnrepository.com/artifact/org.hibernate/hibernate-commons-annotations](url), **pom.xml** changed to 
```
<!-- https://mvnrepository.com/artifact/org.hibernate.common/hibernate-commons-annotations -->
<dependency>
    <groupId>org.hibernate.common</groupId>
    <artifactId>hibernate-commons-annotations</artifactId>
    <version>5.0.1.Final</version>
</dependency>
```

-  I'm deploy on Tomcat **7.0** or **8.0** , Project entrance is [http://localhost:8080/your application context name /user/loginPage](url), I do not have deploy on  jetty , I feel very sorry

##  if you have an issue , I hope you can point it out
